### PR TITLE
Patch to add load average monitoring.

### PR DESCRIPTION
**Pull request by clockley**

### CODE REVIEW

**Comment by troglobit** [comment]
Neat!  I'll do some style cleanup and squash your commits before merging.

Cheers!

**Comment by troglobit** [comment]
Merged to master, with some fixups, as 955ba33. 

Thank you for the patch! :smiley: :+1:

**Comment by troglobit** [comment]
@clockley Minor question post-merge; what was the unused `get_cpu_count()` function supposed to do?

**Comment by clockley** [comment]
The get_cpu_count() should be multiplied by 0.8 to set the default value for load_reboot and load_warn.

[Edit]

After reading this https://prutser.wordpress.com/2012/04/23/understanding-linux-load-average-part-1
I think a get_cpu_count() * .90 is a better default.

**Comment by troglobit** [comment]
Ah, as I suspected then, thanks! :+1: 

(The code to get the number of cores was however wrong ... fixed it to use `sysconf()` instead of `sysinfo()`)

I've been refactoring the code quite a bit, making the loadavg checker and the trigger levels independent of the number of cores.  I've also reworked the whole of watchdogd for adding a process monitor with instrumentation API.

Have a look if you can, I'd very much like your feedback!

**Comment by clockley** [comment]
The load average code looks great. Unfortunately I'm unable to build it because git clone is not copying the files in the libite and libuev folders.

**Comment by troglobit** [comment]
Great to hear, thanks! :smiley: 

After cloning the repo, you have to

    git submodule update --init

... guess I should put that in a HACKING file.

**Pull request closed without merging**
